# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: golem15.apparatus::lang.job.label

# Model Form Field configuration
form: $/golem15/apparatus/models/job/fields.yaml

# Model Class name
modelClass: Golem15\Apparatus\Models\Job

# Default redirect location
defaultRedirect: golem15/apparatus/jobs

# Create page
create:
    title: golem15.apparatus::lang.job.create_title
    redirect: golem15/apparatus/jobs/update/:id
    redirectClose: golem15/apparatus/jobs

# Update page
update:
    title: golem15.apparatus::lang.job.update_title
    redirect: golem15/apparatus/jobs
    redirectClose: golem15/apparatus/jobs

# Preview page
preview:
    title: golem15.apparatus::lang.job.preview_title
